# Generated by Django 3.2.1 on 2021-10-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reason',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
