# Generated by Django 3.2.1 on 2021-10-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211018_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reason',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
