# Generated by Django 3.2.1 on 2021-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=1237, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
